require "ruby_collections/max_heap"
require "ruby_collections/min_heap"
require "ruby_collections/stack"
require "ruby_collections/linked_list"
require "ruby_collections/deque"
require "ruby_collections/union_find"